--------------------------------------------------------
--  Constraints for Table CFG_JOB
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("JOB_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" ADD CONSTRAINT "CFG_JOB_PK" PRIMARY KEY ("JOB_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_JOB" MODIFY ("JOB_ID" NOT NULL ENABLE);
