--------------------------------------------------------
--  Constraints for Table CFG_HRT_TALENT_POOL
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL" ADD CONSTRAINT "CFG_HRT_TALENT_POOL_PK" PRIMARY KEY ("POOL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL" MODIFY ("POOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL" MODIFY ("POOL_ID" NOT NULL ENABLE);
