--------------------------------------------------------
--  Constraints for Table CFG_GRADES_IN_LADDER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" ADD CONSTRAINT "CFG_GRADES_IN_LADDER_PK" PRIMARY KEY ("GRADES_IN_LADDER_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("GRADE_SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("GRADE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("GRADE_LADDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("GRADES_IN_LADDER_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADES_IN_LADDER" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
