--------------------------------------------------------
--  Constraints for Table CFG_HRT_PROFILE_RELATION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_RELATION" ADD CONSTRAINT "CFG_HRT_PROFILE_RELATION_PK" PRIMARY KEY ("PROFILE_RELATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_RELATION" MODIFY ("RELATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_RELATION" MODIFY ("PROFILE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_RELATION" MODIFY ("PROFILE_RELATION_ID" NOT NULL ENABLE);
