--------------------------------------------------------
--  Constraints for Table CFG_ORGANIZATION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" ADD CONSTRAINT "CFG_ORGANIZATION_PK" PRIMARY KEY ("ORGANIZATION_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("CLASSIFICATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("LEGAL_ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("ORGANIZATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
