--------------------------------------------------------
--  Constraints for Table CFG_GRADE_RATE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("ACTIVE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("ANNUALIZATION_FACTOR" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("RATE_FREQUENCY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("CURRENCY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("RATE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("LEGISLATIVE_DATA_GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("GRADE_RATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" ADD CONSTRAINT "CFG_GRADE_RATE_PK" PRIMARY KEY ("RATE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_RATE" MODIFY ("RATE_ID" NOT NULL ENABLE);
