--------------------------------------------------------
--  DDL for Table CFG_HRT_CONTENT_ITEM_RLAT
--------------------------------------------------------

  CREATE TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" 
   (	"CONTENT_ITEM_RLAT_ID" NUMBER, 
	"CONTENT_ITEM_ID" NUMBER, 
	"CONTENT_ITEM_NAME" VARCHAR2(700 BYTE), 
	"CONTENT_TYPE_ID" NUMBER, 
	"CONTEXT_NAME" VARCHAR2(30 BYTE), 
	"DATE_FROM" DATE, 
	"DATE_TO" DATE, 
	"MANDATORY" VARCHAR2(30 BYTE), 
	"RELATED_CONTENT_ITEM_ID" NUMBER, 
	"RELATED_CONTENT_ITEM_NAME" VARCHAR2(700 BYTE), 
	"RELATED_CONTENT_TYPE_ID" VARCHAR2(30 BYTE), 
	"RLAT_CONTENT_TYPE_CONTEXT_NAME" VARCHAR2(30 BYTE), 
	"RELATIONSHIP_CODE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."CONTENT_ITEM_RLAT_ID" IS 'ContentItemRlatId';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."CONTENT_ITEM_ID" IS 'ContentItemId';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."CONTENT_ITEM_NAME" IS 'ContentItemName';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."CONTENT_TYPE_ID" IS 'ContentTypeId';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."CONTEXT_NAME" IS 'ContextName';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."DATE_FROM" IS 'DateFrom';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."DATE_TO" IS 'DateTo';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."MANDATORY" IS 'Mandatory';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."RELATED_CONTENT_ITEM_ID" IS 'RelatedContentItemId';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."RELATED_CONTENT_ITEM_NAME" IS 'RelatedContentItemName';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."RELATED_CONTENT_TYPE_ID" IS 'RelatedContentTypeId';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."RLAT_CONTENT_TYPE_CONTEXT_NAME" IS 'RelatedContentTypeContextName';
   COMMENT ON COLUMN "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT"."RELATIONSHIP_CODE" IS 'RelationshipCode';
