--------------------------------------------------------
--  Constraints for Table CFG_SALARY_BASIS_COMPONENT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS_COMPONENT" ADD CONSTRAINT "CFG_SALARY_BASIS_COMPONENT_PK" PRIMARY KEY ("LOOKUP_USAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS_COMPONENT" MODIFY ("SALARY_BASIS_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS_COMPONENT" MODIFY ("ATTRIBUTE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS_COMPONENT" MODIFY ("LOOKUP_USAGE_ID" NOT NULL ENABLE);
