--------------------------------------------------------
--  Constraints for Table CFG_GRADE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" ADD CONSTRAINT "CFG_GRADE_PK" PRIMARY KEY ("GRADE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("GRADE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("ACTIVE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE" MODIFY ("GRADE_ID" NOT NULL ENABLE);
