--------------------------------------------------------
--  Constraints for Table CFG_ACTION_REASON_USAGE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ACTION_REASON_USAGE" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ACTION_REASON_USAGE" MODIFY ("ACTION_REASON_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ACTION_REASON_USAGE" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ACTION_REASON_USAGE" ADD CONSTRAINT "CFG_ACTION_REASON_USAGE_PK" PRIMARY KEY ("ACTION_REASON_USAGE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ACTION_REASON_USAGE" MODIFY ("ACTION_REASON_USAGE_ID" NOT NULL ENABLE);
