--------------------------------------------------------
--  Constraints for Table CFG_DEPARTMENT_TREE_VERSION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("TREE_VERSION_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("TREE_VERSION_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" ADD CONSTRAINT "CFG_DEPARTMENT_TREE_VERSIO_PK" PRIMARY KEY ("TREE_STRUCTURE_CODE", "TREE_CODE", "DEPARTMENT_TREE_VERSION_ID")
  USING INDEX (CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSIO_PK1" ON "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" ("TREE_STRUCTURE_CODE", "TREE_CODE", "DEPARTMENT_TREE_VERSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("TREE_VERSION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("TREE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("TREE_STRUCTURE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" MODIFY ("DEPARTMENT_TREE_VERSION_ID" NOT NULL ENABLE);
