--------------------------------------------------------
--  DDL for Index CFG_DEPARTMENT_TREE_VERSIO_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSIO_PK1" ON "HCM_ADMIN"."CFG_DEPARTMENT_TREE_VERSION" ("TREE_STRUCTURE_CODE", "TREE_CODE", "DEPARTMENT_TREE_VERSION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
