--------------------------------------------------------
--  Constraints for Table CFG_JOB_FAMILY
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" ADD CONSTRAINT "CFG_JOB_FAMILY_PK" PRIMARY KEY ("JOB_FAMILY_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" MODIFY ("ACTIVE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" MODIFY ("JOB_FAMILY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" MODIFY ("JOB_FAMILY_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_FAMILY" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
