--------------------------------------------------------
--  Constraints for Table CFG_GRADE_LADDER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" MODIFY ("ACTIVE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" ADD CONSTRAINT "CFG_GRADE_LADDER_PK" PRIMARY KEY ("GRADE_LADDER_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_LADDER" MODIFY ("GRADE_LADDER_ID" NOT NULL ENABLE);
