--------------------------------------------------------
--  DDL for Index CFG_ORG_CLASSIFICATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_ORG_CLASSIFICATION_PK" ON "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" ("ORG_UNIT_CLASSIFICATION_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
