--------------------------------------------------------
--  Constraints for Table CFG_DOCUMENT_TYPE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("ISSUING_LOCATION_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("ISSUING_COUNTRY_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("ISSUING_AUTHORITY_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("ISSUED_DATE_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DOCUMENT_NUMBER_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DOCUMENT_NAME_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DATE_TO_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DATE_FROM_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("COMMENTS_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" ADD CONSTRAINT "CFG_DOCUMENT_TYPE_PK" PRIMARY KEY ("DOCUMENT_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_DOCUMENT_TYPE" MODIFY ("DOCUMENT_TYPE_ID" NOT NULL ENABLE);
