--------------------------------------------------------
--  DDL for Index CFG_LOCATION_LEG_EXTRA_INF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INF_PK" ON "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" ("LOCATION_EXTRA_INFO_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
