--------------------------------------------------------
--  Constraints for Table CFG_HRT_RATING_LEVEL
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" ADD CONSTRAINT "CFG_HRT_RATING_LEVEL_PK" PRIMARY KEY ("RATING_LEVEL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" MODIFY ("RATING_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" MODIFY ("RATING_LEVEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" MODIFY ("RATING_MODEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_LEVEL" MODIFY ("RATING_LEVEL_ID" NOT NULL ENABLE);
