--------------------------------------------------------
--  Constraints for Table CFG_ORGANIZATION_INFO
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("PER_ORG_INFO_EFF" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("SEQUENCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("ORG_INFORMATION_CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("CLASSIFICATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("ORGANIZATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" ADD CONSTRAINT "CFG_ORGANIZATION_INFO_PK" PRIMARY KEY ("ORG_INFORMATION_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_INFO" MODIFY ("ORG_INFORMATION_ID" NOT NULL ENABLE);
