--------------------------------------------------------
--  Constraints for Table CFG_ORGANIZATION_CLASS
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" ADD CONSTRAINT "CFG_ORG_CLASSIFICATION_PK" PRIMARY KEY ("ORG_UNIT_CLASSIFICATION_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" MODIFY ("CLASSIFICATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" MODIFY ("ORGANIZATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" MODIFY ("ORG_UNIT_CLASSIFICATION_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_CLASS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
