--------------------------------------------------------
--  Constraints for Table CFG_HRT_PROFILE_ITEM
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_ITEM" ADD CONSTRAINT "CFG_HRT_PROFILE_ITEM_PK" PRIMARY KEY ("PROFILE_ITEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_ITEM" MODIFY ("DATE_FROM" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_ITEM" MODIFY ("CONTENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_ITEM" MODIFY ("PROFILE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_PROFILE_ITEM" MODIFY ("PROFILE_ITEM_ID" NOT NULL ENABLE);
