--------------------------------------------------------
--  Constraints for Table CFG_ORGANIZATION_TREE_NODE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" ADD CONSTRAINT "CFG_ORGANIZATION_TREE_NODE_PK" PRIMARY KEY ("TREE_STRUCTURE_CODE", "TREE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("CLASSIFICATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("ORGANIZATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("PARENT_CLASSIFICATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("PARENT_ORGANIZATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("TREE_VERSION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("TREE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("TREE_STRUCTURE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_NODE" MODIFY ("ORGANIZATION_TREE_NODE_ID" NOT NULL ENABLE);
