--------------------------------------------------------
--  DDL for Index CFG_ORGANIZATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_ORGANIZATION_PK" ON "HCM_ADMIN"."CFG_ORGANIZATION" ("ORGANIZATION_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
