--------------------------------------------------------
--  Constraints for Table CFG_ORGANIZATION_TREE_VERSION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" ADD CONSTRAINT "CFG_ORGANIZATION_TREE_VERS_PK" PRIMARY KEY ("TREE_STRUCTURE_CODE", "TREE_CODE")
  USING INDEX (CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERS_PK1" ON "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" ("TREE_STRUCTURE_CODE", "TREE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("TREE_VERSION_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("TREE_VERSION_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("TREE_VERSION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("TREE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("TREE_STRUCTURE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_ORGANIZATION_TREE_VERSION" MODIFY ("ORGANIZATION_TREE_VERSION_ID" NOT NULL ENABLE);
