--------------------------------------------------------
--  Constraints for Table CFG_GRADE_STEP
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" ADD CONSTRAINT "CFG_GRADE_STEP_PK" PRIMARY KEY ("GRADE_STEP_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("CEILING_STEP_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("GRADE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_GRADE_STEP" MODIFY ("GRADE_STEP_ID" NOT NULL ENABLE);
