--------------------------------------------------------
--  Constraints for Table CFG_POSITION_EXTRA_INFO
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" ADD CONSTRAINT "CFG_POSITION_EXTRA_INFO_PK" PRIMARY KEY ("POSITION_EXTRA_INFO_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("PER_POSITIONS_EIT_EFF" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("POEI_ATTRIBUTE_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("POSITION_EXTRA_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_EXTRA_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
