--------------------------------------------------------
--  Constraints for Table CFG_DEPARTMENT_TREE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" MODIFY ("TREE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" MODIFY ("TREE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" ADD CONSTRAINT "CFG_DEPARTMENT_TREE_PK" PRIMARY KEY ("TREE_STRUCTURE_CODE", "TREE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" MODIFY ("TREE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" MODIFY ("TREE_STRUCTURE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_DEPARTMENT_TREE" MODIFY ("DEPARTMENT_TREE_ID" NOT NULL ENABLE);
