--------------------------------------------------------
--  Constraints for Table CFG_LOCATION_LEG_EXTRA_INFO
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" ADD CONSTRAINT "CFG_LOCATION_LEG_EXTRA_INF_PK" PRIMARY KEY ("LOCATION_EXTRA_INFO_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("PER_LOCATION_LEG_EFF" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("LOCATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("SEQUENCE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("LOCATION_EXTRA_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_LOCATION_LEG_EXTRA_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
