--------------------------------------------------------
--  Constraints for Table CFG_HRT_TALENT_POOL_MEMBER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" ADD CONSTRAINT "CFG_HRT_TALENT_POOL_MEMBER_PK" PRIMARY KEY ("POOL_MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("POOL_MEMBER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("MEMBER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("POOL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("POOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_MEMBER" MODIFY ("POOL_MEMBER_ID" NOT NULL ENABLE);
