--------------------------------------------------------
--  DDL for Index CFG_DEPARTMENT_TREE_NODE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."CFG_DEPARTMENT_TREE_NODE_PK" ON "HCM_ADMIN"."CFG_DEPARTMENT_TREE_NODE" ("TREE_CODE", "TREE_STRUCTURE_CODE", "TREE_VERSION_ID", "DEPARTMENT_TREE_NODE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
