--------------------------------------------------------
--  Constraints for Table CFG_SALARY_BASIS
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("SALARY_BASIS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("LEGISLATIVE_DATA_GROUP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("INPUT_VALUE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("GRADE_RATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("ELEMENT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("COMPONENT_USAGE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("SALARY_BASIS_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" ADD CONSTRAINT "CFG_SALARY_BASIS_PK" PRIMARY KEY ("SALARY_BASIS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_SALARY_BASIS" MODIFY ("SALARY_BASIS_ID" NOT NULL ENABLE);
