--------------------------------------------------------
--  DDL for Index CFG_ACTION_N1
--------------------------------------------------------

  CREATE INDEX "HCM_ADMIN"."CFG_ACTION_N1" ON "HCM_ADMIN"."CFG_ACTION" (UPPER("ACTION_CODE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
