--------------------------------------------------------
--  Constraints for Table CFG_HRT_CONTENT_ITEM_RLAT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" ADD CONSTRAINT "CFG_HRT_CONTENT_ITEM_RLAT_PK" PRIMARY KEY ("CONTENT_ITEM_RLAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" MODIFY ("RLAT_CONTENT_TYPE_CONTEXT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" MODIFY ("RELATED_CONTENT_ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" MODIFY ("CONTEXT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" MODIFY ("CONTENT_ITEM_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_CONTENT_ITEM_RLAT" MODIFY ("CONTENT_ITEM_RLAT_ID" NOT NULL ENABLE);
