--------------------------------------------------------
--  Constraints for Table CFG_POSITION_LEG_EXTRA_INFO
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" ADD CONSTRAINT "CFG_POSITION_LEG_EXTRA_INF_PK" PRIMARY KEY ("POSITION_LEG_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" MODIFY ("PER_POSITIONS_LEG_EFF" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_POSITION_LEG_EXTRA_INFO" MODIFY ("POSITION_LEG_ID" NOT NULL ENABLE);
