--------------------------------------------------------
--  Constraints for Table CFG_HRT_TALENT_POOL_OWNER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" MODIFY ("POOL_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" MODIFY ("POOL_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" MODIFY ("OWNER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" ADD CONSTRAINT "CFG_HRT_TALENT_POOL_OWNER_PK" PRIMARY KEY ("POOL_OWNER_ID")
  USING INDEX (CREATE INDEX "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER_N1" ON "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" ("POOL_OWNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_TALENT_POOL_OWNER" MODIFY ("POOL_OWNER_ID" NOT NULL ENABLE);
