--------------------------------------------------------
--  Constraints for Table CFG_JOB_LEG
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" ADD CONSTRAINT "CFG_JOB_LEG_PK" PRIMARY KEY ("JOB_LEG_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("PER_JOBS_LEG_EFF" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("SET_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("JOB_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("INFORMATION_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_JOB_LEG" MODIFY ("JOB_LEG_ID" NOT NULL ENABLE);
