--------------------------------------------------------
--  Constraints for Table CFG_HRT_RATING_CATEGORY
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_CATEGORY" ADD CONSTRAINT "CFG_HRT_RATING_CATEGORY_PK" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_CATEGORY" MODIFY ("RATING_MODEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."CFG_HRT_RATING_CATEGORY" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
