--------------------------------------------------------
--  File created - Monday-January-01-2018   
--------------------------------------------------------
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RDESC.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RLAT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_KEYWORD.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_RELATION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_CATEGORY.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_LEVEL.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_MODEL.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_MEMBER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_OWNER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERSION_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ADDRESS.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESPONSIBILITY.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGN_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_GRADE_STEP.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_WM.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CITIZENSHIP.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CONTRACT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DELIVERY_METHOD.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_ATTACHMENT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DRIVERS_LICENSE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPL_TERM_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_GS.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_WM.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ETHNICITY.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_IMAGE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_LEGISLATIVE_DATA.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PASSPORT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PHONE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_RELIGION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_VISA.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSIO_PK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RDESC_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RDESC_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RLAT_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_KEYWORD_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_KEYWORD_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_RELATION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_RELATION_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_RELATION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_CATEGORY_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_CATEGORY_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_LEVEL_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_LEVEL_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_LEVEL_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_MODEL_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_MODEL_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_MEMBER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_MEMBER_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_MEMBER_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_OWNER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_OWNER_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_OWNER_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_F1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INF_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO_F1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N3_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_U1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N3_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORG_CLASSIFICATION_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERS_PK1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N3_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N4_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N5_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N6_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N7_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_FK1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INF_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_N2_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_N1_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE_PK_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ADDRESS_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N17.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N18.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N19.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N20.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N8.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N9.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESPONSIBI_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N21.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N10.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N11.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N12.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N13.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N14.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N15.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESP_N16.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGN_EXTRA_IN_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGN_EXTRA_IN_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK9.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK8.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N9.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N8.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_GRADE_S_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_WM_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_WM_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CITIZENSHIP_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CITIZENSHIP_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CONTRACT_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CONTRACT_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CONTRACT_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DELIVERY_METHOD_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DELIVERY_METHOD_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_ATTACHMEN_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_ATTACHMENT_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DRIVERS_LICENSE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DRIVERS_LICENSE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPL_TERM_EXTRA_IN_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPL_TERM_EXTRA_IN_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N8.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N9.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK8.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_FK9.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_GS_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_WM_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_WM_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ETHNICITY_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ETHNICITY_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_IMAGE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_IMAGE_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_LEGISLATIVE_DATA_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_LEGISLATIVE_DATA_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIER_F1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIER_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIER_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PASSPORT_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PASSPORT_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PHONE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PHONE_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_RELIGION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_RELIGION_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_U2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_VISA_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_VISA_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP_FK2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_WORKER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_WORKER_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_WORKER_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_WORKER_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_EXTRA_INFO_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_EXTRA_INFO_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_EXTRA_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RDESC_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_CONTENT_ITEM_RLAT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_ITEM_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_KEYWORD_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_PROFILE_RELATION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_CATEGORY_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_LEVEL_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_RATING_MODEL_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_MEMBER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_POOL_OWNER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_HRT_TALENT_PROFILE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERSION_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE_CONSTRAINT_1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ADDRESS_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_AREA_OF_RESPONSIBILITY_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGN_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_GRADE_STEP_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_MANAGER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ASSIGNMENT_WM_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CITIZENSHIP_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_CONTRACT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DELIVERY_METHOD_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_ATTACHMENT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DOCUMENT_RECORD_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_DRIVERS_LICENSE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMAIL_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPL_TERM_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_GS_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_MGR_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_EMPLOYMENT_TERM_WM_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_ETHNICITY_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_IMAGE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_LEGISLATIVE_DATA_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NAME_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_NATIONAL_IDENTIFIER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PASSPORT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_PHONE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_RELIGION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_INFORMATION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_USER_MANUAL_ROLE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_VISA_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORK_RELATIONSHIP_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\STG_PER_WORKER_EXTRA_INFO_CONSTRAINT.sql
