--------------------------------------------------------
--  File created - Monday-December-18-2017   
--------------------------------------------------------
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERSION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSIO_PK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_F1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INF_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO_F1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_U1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORG_CLASSIFICATION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERS_PK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N3.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N4.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N5.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N6.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_N7.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_FK1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INF_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_N2.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_N1.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE_PK.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ACTION_REASON_USAGE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_NODE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DEPARTMENT_TREE_VERSION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_DOCUMENT_TYPE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_LADDER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_RATE_VALUE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADE_STEP_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_GRADES_IN_LADDER_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_FAMILY_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_LEG_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_JOB_VALID_GRADE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_LEG_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_LOCATION_OTHER_ADDRESS_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_CLASS_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_NODE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_ORGANIZATION_TREE_VERSION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_LEG_EXTRA_INFO_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_POSITION_VALID_GRADE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_SALARY_BASIS_COMPONENT_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_CONSTRAINT.sql
@D:\Users\us52031\Desktop\Reference Materials\HDL Files\CHub\CFG_STEP_RATE_VALUE_CONSTRAINT.sql
