--------------------------------------------------------
--  DDL for Index STG_PER_ASSIGNMENT_MANAGER_N4
--------------------------------------------------------

  CREATE INDEX "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER_N4" ON "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" ("PERSON_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
