--------------------------------------------------------
--  Constraints for Table STG_PER_CITIZENSHIP
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_CITIZENSHIP" MODIFY ("CITIZENSHIP_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_CITIZENSHIP" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_CITIZENSHIP" ADD CONSTRAINT "STG_PER_CITIZENSHIP_PK" PRIMARY KEY ("CITIZENSHIP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_CITIZENSHIP" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_CITIZENSHIP" MODIFY ("CITIZENSHIP_ID" NOT NULL ENABLE);
