--------------------------------------------------------
--  Constraints for Table STG_PER_DOCUMENT_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" ADD CONSTRAINT "STG_PER_DOCUMENT_ATTACHMEN_PK" PRIMARY KEY ("ATTACHED_DOCUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("URL_OR_TEXT_OR_FILE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_ATTACHMENT" MODIFY ("ATTACHED_DOCUMENT_ID" NOT NULL ENABLE);
