--------------------------------------------------------
--  Constraints for Table STG_PER_ASSIGNMENT_WM
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" ADD CONSTRAINT "STG_PER_ASSIGN_WORK_MEASUR_PK" PRIMARY KEY ("ASSIGN_WORK_MEASURE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX (CREATE UNIQUE INDEX "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM_PK" ON "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" ("ASSIGN_WORK_MEASURE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_WM" MODIFY ("ASSIGN_WORK_MEASURE_ID" NOT NULL ENABLE);
