--------------------------------------------------------
--  Constraints for Table STG_PER_ASSIGNMENT_MANAGER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" ADD CONSTRAINT "STG_PER_ASSIGNMENT_MANAGER_PK" PRIMARY KEY ("ASSIGNMENT_SUPERVISOR_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("MANAGER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("MANAGER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_MANAGER" MODIFY ("ASSIGNMENT_SUPERVISOR_ID" NOT NULL ENABLE);
