--------------------------------------------------------
--  Constraints for Table STG_PER_LEGISLATIVE_DATA
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_LEGISLATIVE_DATA" ADD CONSTRAINT "STG_PER_LEGISLATIVE_DATA_PK" PRIMARY KEY ("PERSON_LEGISLATIVE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_LEGISLATIVE_DATA" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_LEGISLATIVE_DATA" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_LEGISLATIVE_DATA" MODIFY ("PERSON_LEGISLATIVE_ID" NOT NULL ENABLE);
