--------------------------------------------------------
--  Constraints for Table STG_PER_PASSPORT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_PASSPORT" ADD CONSTRAINT "STG_PER_PASSPORT_PK" PRIMARY KEY ("PASSPORT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_PASSPORT" MODIFY ("PASSPORT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_PASSPORT" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_PASSPORT" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_PASSPORT" MODIFY ("PASSPORT_ID" NOT NULL ENABLE);
