--------------------------------------------------------
--  Constraints for Table STG_PER_EMPLOYMENT_TERM_MGR
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" ADD CONSTRAINT "STG_PER_EMPLOYMENT_TERM_MGR_PK" PRIMARY KEY ("ASSIGNMENT_SUPERVISOR_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("MANAGER_PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("MANAGER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" MODIFY ("ASSIGNMENT_SUPERVISOR_ID" NOT NULL ENABLE);
