--------------------------------------------------------
--  DDL for Index STG_PER_EMPLOYMENT_TERM_MGR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR_PK" ON "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_MGR" ("ASSIGNMENT_SUPERVISOR_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
