--------------------------------------------------------
--  Constraints for Table STG_PER_CONTRACT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_CONTRACT" ADD CONSTRAINT "STG_PER_CONTRACT_PK" PRIMARY KEY ("CONTRACT_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_CONTRACT" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_CONTRACT" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_CONTRACT" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
