--------------------------------------------------------
--  Constraints for Table STG_PER_USER_MANUAL_ROLE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_USER_MANUAL_ROLE" ADD CONSTRAINT "STG_PER_USER_MANUAL_ROLE_PK" PRIMARY KEY ("PERSON_USER_MANUAL_ROLES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_USER_MANUAL_ROLE" MODIFY ("PERSON_USER_MANUAL_ROLES_ID" NOT NULL ENABLE);
