--------------------------------------------------------
--  Constraints for Table STG_PER_EMPLOYMENT_TERM_WM
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" ADD CONSTRAINT "STG_PER_EMPLOYMENT_TERM_WM_PK" PRIMARY KEY ("ASSIGN_WORK_MEASURE_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("UNIT" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_WM" MODIFY ("ASSIGN_WORK_MEASURE_ID" NOT NULL ENABLE);
