--------------------------------------------------------
--  Constraints for Table STG_PER_DELIVERY_METHOD
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" ADD CONSTRAINT "STG_PER_DELIVERY_METHOD_PK" PRIMARY KEY ("DELIVERY_METHOD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" MODIFY ("COMM_DLVRY_METHOD" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" MODIFY ("PREFERRED_ORDER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DELIVERY_METHOD" MODIFY ("DELIVERY_METHOD_ID" NOT NULL ENABLE);
