--------------------------------------------------------
--  Constraints for Table STG_PER_WORK_RELATIONSHIP
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" ADD CONSTRAINT "STG_PER_WORK_RELATIONSHIP_PK" PRIMARY KEY ("PERIOD_OF_SERVICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("WORKER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("LEGAL_EMPLOYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_WORK_RELATIONSHIP" MODIFY ("PERIOD_OF_SERVICE_ID" NOT NULL ENABLE);
