--------------------------------------------------------
--  Constraints for Table STG_PER_EMPLOYMENT_TERM_GS
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" ADD CONSTRAINT "STG_PER_EMPLOYMENT_TERM_GS_PK" PRIMARY KEY ("ASSIGN_GRADE_STEP_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("GRADE_STEP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_GS" MODIFY ("ASSIGN_GRADE_STEP_ID" NOT NULL ENABLE);
