--------------------------------------------------------
--  Constraints for Table STG_PER_NAME
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" ADD CONSTRAINT "STG_PER_NAME_PK" PRIMARY KEY ("PERSON_NAME_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("NAME_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NAME" MODIFY ("PERSON_NAME_ID" NOT NULL ENABLE);
