--------------------------------------------------------
--  DDL for Index STG_PER_AREA_OF_RESP_N2
--------------------------------------------------------

  CREATE INDEX "HCM_ADMIN"."STG_PER_AREA_OF_RESP_N2" ON "HCM_ADMIN"."STG_PER_AREA_OF_RESPONSIBILITY" ("ORGANIZATION_HIERARCHY_ID", "TOP_ORGANIZATION_ID", "HIERARCHY_LEVELS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
