--------------------------------------------------------
--  Constraints for Table STG_PER_ETHNICITY
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" ADD CONSTRAINT "STG_PER_ETHNICITY_PK" PRIMARY KEY ("ETHNICITY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" MODIFY ("PRIMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" MODIFY ("ETHNICITY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ETHNICITY" MODIFY ("ETHNICITY_ID" NOT NULL ENABLE);
