--------------------------------------------------------
--  Constraints for Table STG_PER_EMAIL
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMAIL" ADD CONSTRAINT "STG_PER_EMAIL_PK" PRIMARY KEY ("EMAIL_ADDRESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMAIL" MODIFY ("EMAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMAIL" MODIFY ("EMAIL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMAIL" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMAIL" MODIFY ("EMAIL_ADDRESS_ID" NOT NULL ENABLE);
