--------------------------------------------------------
--  Constraints for Table STG_PER_RELIGION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" ADD CONSTRAINT "STG_PER_RELIGION_PK" PRIMARY KEY ("RELIGION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" MODIFY ("PRIMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" MODIFY ("RELIGION" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_RELIGION" MODIFY ("RELIGION_ID" NOT NULL ENABLE);
