--------------------------------------------------------
--  Constraints for Table STG_PER_ASSIGNMENT
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("PRIMARY_ASSIGNMENT_FLAG" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("WORK_TERMS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("EFFECTIVE_LATEST_CHANGE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("EFFECTIVE_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("LEGAL_EMPLOYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("WORKER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("ASSIGNMENT_STATUS_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("BUSINESS_UNIT_SHORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
