--------------------------------------------------------
--  Constraints for Table STG_PER_USER_INFORMATION
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_USER_INFORMATION" ADD CONSTRAINT "STG_PER_USER_INFORMATION_PK" PRIMARY KEY ("PERSON_USER_INFORMATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_USER_INFORMATION" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_USER_INFORMATION" MODIFY ("PERSON_USER_INFORMATION_ID" NOT NULL ENABLE);
