--------------------------------------------------------
--  Constraints for Table STG_PER_EMPL_TERM_EXTRA_INFO
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" ADD CONSTRAINT "STG_PER_EMPL_TERM_EXTRA_IN_PK" PRIMARY KEY ("ASSIGNMENT_EXTRA_INFO_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "EFFECTIVE_SEQUENCE", "EFFECTIVE_LATEST_CHANGE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("INFORMATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("AEI_INFORMATION_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("ASSIGNMENT_EXTRA_INFO_ID" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("EFF_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPL_TERM_EXTRA_INFO" MODIFY ("PER_ASSIGNMENT_EIT_EFF" NOT NULL ENABLE);
