--------------------------------------------------------
--  DDL for Index STG_PER_ASSIGN_EXTRA_IN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."STG_PER_ASSIGN_EXTRA_IN_PK" ON "HCM_ADMIN"."STG_PER_ASSIGN_EXTRA_INFO" ("ASSIGNMENT_EXTRA_INFO_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "EFFECTIVE_SEQUENCE", "EFFECTIVE_LATEST_CHANGE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
