--------------------------------------------------------
--  DDL for Index STG_PER_NATIONAL_IDENTIFIER_N2
--------------------------------------------------------

  CREATE INDEX "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER_N2" ON "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" (UPPER("NATIONAL_IDENTIFIER_NUMBER")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
