--------------------------------------------------------
--  Constraints for Table STG_PER_EMPLOYMENT_TERM
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ASSIGNMENT_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "EFFECTIVE_LATEST_CHANGE", "EFFECTIVE_SEQUENCE")
  USING INDEX (CREATE UNIQUE INDEX "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM_PK" ON "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" ("ASSIGNMENT_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE", "EFFECTIVE_LATEST_CHANGE", "EFFECTIVE_SEQUENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" )  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("BUSINESS_UNIT_SHORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("ASSIGNMENT_STATUS_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("WORKER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("DATE_START" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("LEGAL_EMPLOYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("EFFECTIVE_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("EFFECTIVE_LATEST_CHANGE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_EMPLOYMENT_TERM" MODIFY ("ASSIGNMENT_ID" NOT NULL ENABLE);
