--------------------------------------------------------
--  Constraints for Table STG_PER_NATIONAL_IDENTIFIER
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" ADD CONSTRAINT "STG_PER_NATIONAL_IDENTIFIE_PK" PRIMARY KEY ("NATIONAL_IDENTIFIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" MODIFY ("NATIONAL_IDENTIFIER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" MODIFY ("NATIONAL_IDENTIFIER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" MODIFY ("NATIONAL_IDENTIFIER_ID" NOT NULL ENABLE);
