--------------------------------------------------------
--  Constraints for Table STG_PER_ASSIGNMENT_GRADE_STEP
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" ADD CONSTRAINT "STG_PER_ASSIGNMENT_GRADE_S_PK" PRIMARY KEY ("ASSIGN_GRADE_STEP_ID", "EFFECTIVE_START_DATE", "EFFECTIVE_END_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("ACTION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("GRADE_STEP_NAME" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("ASSIGNMENT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("EFFECTIVE_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("EFFECTIVE_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_ASSIGNMENT_GRADE_STEP" MODIFY ("ASSIGN_GRADE_STEP_ID" NOT NULL ENABLE);
