--------------------------------------------------------
--  Constraints for Table STG_PER_DRIVERS_LICENSE
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" ADD CONSTRAINT "STG_PER_DRIVERS_LICENSE_PK" PRIMARY KEY ("DRIVERS_LICENSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" MODIFY ("LICENSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" MODIFY ("LICENSE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" MODIFY ("LEGISLATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DRIVERS_LICENSE" MODIFY ("DRIVERS_LICENSE_ID" NOT NULL ENABLE);
