--------------------------------------------------------
--  Constraints for Table STG_PER_DOCUMENT_RECORD
--------------------------------------------------------

  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" ADD CONSTRAINT "STG_PER_DOCUMENT_RECORD_PK" PRIMARY KEY ("DOCUMENTS_OF_RECORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" MODIFY ("DOCUMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" MODIFY ("COUNTRY" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" MODIFY ("PERSON_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" MODIFY ("DOCUMENT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HCM_ADMIN"."STG_PER_DOCUMENT_RECORD" MODIFY ("DOCUMENTS_OF_RECORD_ID" NOT NULL ENABLE);
