--------------------------------------------------------
--  DDL for Index STG_PER_NATIONAL_IDENTIFIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIE_PK" ON "HCM_ADMIN"."STG_PER_NATIONAL_IDENTIFIER" ("NATIONAL_IDENTIFIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
